CREATE TABLE TB_USUARIO (
    CO_USUARIO SERIAL PRIMARY KEY,
    NO_USUARIO VARCHAR(256) NOT NULL,
    DS_EMAIL VARCHAR(1000) NOT NULL,
    DT_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_EXCLUSAO TIMESTAMP
);

CREATE TABLE TB_VENDEDOR (
    CO_USUARIO INTEGER PRIMARY KEY REFERENCES TB_USUARIO(CO_USUARIO),
    NU_CPF CHAR(11) NOT NULL,
    DT_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_EXCLUSAO TIMESTAMP
);

CREATE TABLE TB_ADMINISTRADOR (
    CO_USUARIO INTEGER PRIMARY KEY REFERENCES TB_USUARIO(CO_USUARIO),
    DT_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_EXCLUSAO TIMESTAMP
);

CREATE TABLE TB_CLIENTE (
    CO_USUARIO INTEGER PRIMARY KEY REFERENCES TB_USUARIO(CO_USUARIO),
    NU_CPF CHAR(11),
    DT_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_EXCLUSAO TIMESTAMP
);

CREATE TABLE TB_MATERIAL (
    CO_MATERIAL SERIAL PRIMARY KEY,
    DS_MATERIAL VARCHAR(1000) NOT NULL,
    QT_PORCAO INTEGER NOT NULL,
    TP_UNIDADE_MEDIDA CHAR(1) NOT NULL,
    IE_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    DT_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_EXCLUSAO TIMESTAMP
);

ALTER TABLE TB_MATERIAL
    ADD CHECK ( TP_UNIDADE_MEDIDA IN ( 'C', 'G', 'L', 'U' ) );

CREATE TABLE TB_PRECIFICACAO (
    CO_PRECIFICACAO SERIAL PRIMARY KEY,
    DS_PRECIFICACAO VARCHAR(1000) NOT NULL,
    NU_MARGEM_LUCRO NUMERIC(10,2) NOT NULL,
    DT_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_EXCLUSAO TIMESTAMP
);

CREATE TABLE TB_PRECIFICACAO_MATERIAL (
    CO_PRECIFICACAO_MATERIAL SERIAL PRIMARY KEY,
    CO_MATERIAL INTEGER NOT NULL ,
    CO_PRECIFICACAO INTEGER NOT NULL,
    VL_CUSTO NUMERIC(10, 2) NOT NULL,
    QT_PORCAO_UTILIZADA INTEGER NOT NULL,
    DT_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_EXCLUSAO TIMESTAMP,
    CONSTRAINT fk_precificacao FOREIGN KEY (CO_PRECIFICACAO) REFERENCES TB_PRECIFICACAO(CO_PRECIFICACAO),
    CONSTRAINT fk_material FOREIGN KEY (CO_MATERIAL) REFERENCES TB_MATERIAL(CO_MATERIAL)
);

CREATE TABLE TB_PRODUTO (
    CO_PRODUTO SERIAL PRIMARY KEY,
    DS_PRODUTO VARCHAR(1000) NOT NULL,
    VALOR_UNIT NUMERIC(10, 2) NOT NULL,
    CO_PRECIFICACAO INTEGER NOT NULL REFERENCES TB_PRECIFICACAO(CO_PRECIFICACAO),
    DT_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_EXCLUSAO TIMESTAMP,
    IE_ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE TB_COMPRA (
    CO_COMPRA SERIAL PRIMARY KEY,
    CO_MATERIAL INTEGER NOT NULL REFERENCES TB_MATERIAL(CO_MATERIAL),
    DT_COMPRA DATE NOT NULL,
    QT_ADQUIRIDA INTEGER NOT NULL,
    VL_TOTAL NUMERIC(10,2) NOT NULL,
    QT_RESTANTE INTEGER NOT NULL,
    DT_VALIDADE DATE NOT NULL,
    DT_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TB_PEDIDO (
    CO_PEDIDO SERIAL PRIMARY KEY,
    DS_PEDIDO VARCHAR(1000) NOT NULL,
    VL_TOTAL NUMERIC(10, 2) NOT NULL,
    ST_PEDIDO CHAR(3) NOT NULL,
    CO_CLIENTE INTEGER NOT NULL REFERENCES TB_CLIENTE(CO_USUARIO),
    DT_PEDIDO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_EXCLUSAO TIMESTAMP
);

CREATE TABLE TB_PEDIDO_ITEM (
    CO_PEDIDO INTEGER NOT NULL,
    CO_PRODUTO INTEGER NOT NULL,
    TP_PRODUTO_PEDIDO CHAR(3) NOT NULL,
    VL_UNIT NUMERIC(10, 2) NOT NULL,
    QT_PRODUTO INTEGER NOT NULL,
    DT_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_EXCLUSAO TIMESTAMP,
    PRIMARY KEY (CO_PEDIDO, CO_PRODUTO),
    CONSTRAINT fk_pedido FOREIGN KEY (CO_PEDIDO) REFERENCES TB_PEDIDO(CO_PEDIDO),
    CONSTRAINT fk_produto FOREIGN KEY (CO_PRODUTO) REFERENCES TB_PRODUTO(CO_PRODUTO)
);

CREATE TABLE TB_PAGAMENTOS (
    CO_PAGAMENTO SERIAL PRIMARY KEY,
    CO_PEDIDO INTEGER NOT NULL,
    VL_PAGAMENTO NUMERIC(10, 2) NOT NULL,
    DT_PAGAMENTO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_EXCLUSAO TIMESTAMP,
    FOREIGN KEY (CO_PEDIDO) REFERENCES TB_PEDIDO(CO_PEDIDO)
);
